name: Build-EXE

on:
  push:
    branches:
      - main  # 指定触发Actions的分支，可根据实际情况修改
  workflow_dispatch:  # 也可以手动触发

jobs:
  build:
    runs-on: windows-latest  # 使用最新的Windows环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # 根据你的Python版本修改

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build-EXE
      run: |
        pyinstaller -F -w -i icon.ico main.py

    - name: Create ZIP Archive
      run: |
        Compress-Archive -Path dist/main -DestinationPath dist/MCItemList.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MCItemList  # 可自定义上传的文件名
        path: dist/MCItemList.zip  # 上传zip文件
